## Numpy Practice

This notebook offers a set of excercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the NumPy documentation.

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [14]:
# create a 1-d array using np.array
array_1=np.array([1,2,3,4])
array_1

array([1, 2, 3, 4])

In [13]:
# create a 2-d array using np.array
array_2=np.array([[1,2,3,4],[5,6,7,8]])
array_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
# create a 3-d array using np.array
array_3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
array_3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [19]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
array_1.shape,array_1.dtype,array_1.size,type(array_1),array_1.ndim

((4,), dtype('int32'), 4, numpy.ndarray, 1)

In [20]:
# Attributes of 2-d array
array_2.shape,array_2.dtype,array_2.size,type(array_2),array_2.ndim

((2, 4), dtype('int32'), 8, numpy.ndarray, 2)

In [21]:
# Attributes of 3-d array
array_3.shape,array_3.dtype,array_3.size,type(array_3),array_3.ndim

((1, 3, 3), dtype('int32'), 9, numpy.ndarray, 3)

In [25]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
a1=pd.DataFrame(array_1)
a2=pd.DataFrame(array_2)

In [27]:
a1

0
0  1
1  2
2  3
3  4

In [28]:
a2

0  1  2  3
0  1  2  3  4
1  5  6  7  8

In [30]:
# Create an array of shape (10, 2) with only ones
ones_1=np.ones(shape=(10,2))
ones_1

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_1=np.zeros(shape=(7,2,3))

In [33]:
zeros_1

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [34]:
# Create an array within a range of 0 and 100 with step 3
array_4=np.arange(0,100,3)
array_4

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [38]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.seed(0)
array_5=np.random.randint(0,10,size=(7,2))
array_5

array([[5, 0],
       [3, 3],
       [7, 9],
       [3, 5],
       [2, 4],
       [7, 6],
       [8, 8]])

In [40]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.seed(0)
array_6=np.random.random(size=(3,5))
array_6

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606]])

In [41]:
# Set the random seed to 42
np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
array_7=np.random.randint(0,10,size=(4,6))
array_7

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [45]:

# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
array_8=np.random.randint(1,10,size=(3,7))
# Find the unique numbers in the array you just created
np.unique(array_8)

array([1, 2, 3, 5, 7, 8, 9])

In [49]:
array_8

array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3],
       [1, 8, 3, 3, 1, 5, 7]])

In [47]:
# Find the 0'th index of the latest array you created
array_8[0][0]

2

In [52]:
# Get the first 2 rows of latest array you created
array_8[:2,:]

array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3]])

In [51]:
# Get the first 2 values of the first 2 rows of the latest array
array_8[:2,:2]

array([[2, 5],
       [7, 9]])

In [57]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
array_9=np.random.randint(0,10,size=(3,5))
ones_2=np.ones(shape=(3,5))

In [59]:
# Add the two arrays together
array_9+ones_2

array([[10.,  7.,  9.,  7.,  1.],
       [ 1.,  9.,  9.,  4.,  9.],
       [ 3.,  7.,  6.,  8.,  9.]])

In [60]:
# Create another array of ones of shape (5, 3)
array_10=np.random.randint(0,10,size=(5,3))

In [63]:
# Try add the array of ones and the other most recent array together
array_10.T+array_9

array([[13, 15, 15,  6,  3],
       [ 0, 15, 16,  3, 14],
       [ 4, 11,  8, 16,  9]])

In [66]:
# Create another array of ones of shape (3, 5)
ones_3=np.ones(shape=(3,5))

In [69]:
# Subtract the new array of ones from the other most recent array
array_11=array_10.T-ones_3

In [71]:
# Multiply the ones array with the latest array
array_12=array_11*ones_3

In [72]:
# Take the latest array to the power of 2 using '**'
array_12=array_12**2

In [73]:
array_12

array([[ 9., 64., 36.,  1.,  4.],
       [ 1., 36., 49.,  1., 25.],
       [ 1., 16.,  4., 64.,  0.]])

In [75]:
# Do the same thing with np.square()
np.square(array_11)

array([[ 9., 64., 36.,  1.,  4.],
       [ 1., 36., 49.,  1., 25.],
       [ 1., 16.,  4., 64.,  0.]])

In [76]:
# Find the mean of the latest array using np.mean()
np.mean(array_11)

3.2666666666666666

In [77]:
# Find the maximum of the latest array using np.max()
np.max(array_11)

8.0

In [78]:
# Find the minimum of the latest array using np.min()
np.min(array_11)

-1.0

In [79]:
# Find the standard deviation of the latest array
np.std(array_11)

3.1721006008987516

In [80]:
# Find the variance of the latest array
np.var(array_11)

10.062222222222221

In [87]:
# Reshape the latest array to (3, 5, 1)
array_12=array_11.reshape(3,5,1)
array_12.shape

(3, 5, 1)

In [88]:
# Transpose the latest array
array_12.T

array([[[ 3., -1.,  1.],
        [ 8.,  6.,  4.],
        [ 6.,  7.,  2.],
        [-1., -1.,  8.],
        [ 2.,  5.,  0.]]])

## What does the transpose do?

In [89]:
## Transpose is used to interchange the axis of the arrays.
## It is mainly used which dot product method.

In [90]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array_13=np.random.randint(0,10,size=(3,3))
array_14=np.random.randint(0,10,size=(3,2))

In [91]:
# Perform a dot product on the two newest arrays you created
np.dot(array_13,array_14)

array([[10, 20],
       [28,  0],
       [ 4,  2]])

In [93]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array_15=np.random.randint(0,10,size=(4,3))
array_16=np.random.randint(0,10,size=(4,3))

In [94]:
# Perform a dot product on the two newest arrays you created
np.dot(array_15.T,array_16)

array([[ 39,  77,  79],
       [  4,  30,  15],
       [ 67, 118,  97]])

## Let's now compare arrays.

In [100]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array_17=np.random.randint(0,10,size=(3,3))
array_18=np.random.randint(0,10,size=(3,3))

In [102]:
# Compare the two arrays with '>'
array_17>array_18

array([[ True,  True, False],
       [False,  True, False],
       [ True, False, False]])

In [104]:
# Compare the two arrays with '>='
array_17>=array_18

array([[ True,  True, False],
       [ True,  True,  True],
       [ True, False, False]])

In [107]:
# Sort one of the arrays you just created in ascending orde
## python's sort 
np.sort(array_17)

array([[2, 6, 9],
       [6, 8, 9],
       [0, 1, 3]])

In [108]:
# Sort the indexes of one of the arrays you just created
np.argsort(array_17)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)