In [2]:
import numpy as np

## Datatyps and attributes

In [3]:
##ndarray

a1=np.array([1,2,3])

In [4]:
a1

array([1, 2, 3])

In [5]:
a1.shape

(3,)

In [6]:
type(a1)

numpy.ndarray

In [7]:
a2=np.array([[1,2,3],[4,5,6]])

In [8]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a2[0]

array([1, 2, 3])

In [10]:
type(a2)

numpy.ndarray

In [11]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [12]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [13]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [14]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

In [15]:
a1.size,a2.size,a3.size

(3, 6, 9)

## Using array in pandas's Dataframe

In [16]:
import pandas as pd

In [17]:
df=pd.DataFrame(a2)

In [18]:
df

0  1  2
0  1  2  3
1  4  5  6

## Creating Arrays

In [19]:
sample_array=np.array([1,2,3])

In [20]:
sample_array

array([1, 2, 3])

In [21]:
sample_array.dtype

dtype('int32')

In [22]:
ones=np.ones(5)

In [23]:
ones

array([1., 1., 1., 1., 1.])

In [24]:
ones_2=np.ones((2,3))

In [25]:
ones_2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
zeros=np.zeros((2,5))

In [27]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
range_array=np.arange(0,10,1)

In [29]:
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
random_array=np.random.randint(0,10,4)

In [31]:
random_array

array([3, 9, 6, 9])

In [32]:
random_array.size

4

In [33]:
random_array.shape

(4,)

In [34]:
np.random.seed(0)
random_array_2=np.random.randint(0,10,size=(3,5))

In [35]:
random_array_2

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [36]:
random_array_2.size

15

In [37]:
random_array_2.shape

(3, 5)

In [38]:
random_array_3=np.random.random((5,3))

In [39]:
random_array_3

array([[0.79172504, 0.52889492, 0.56804456],
       [0.92559664, 0.07103606, 0.0871293 ],
       [0.0202184 , 0.83261985, 0.77815675],
       [0.87001215, 0.97861834, 0.79915856],
       [0.46147936, 0.78052918, 0.11827443]])

In [40]:
random_array_3.dtype

dtype('float64')

## Viewing arrays and matrices

In [41]:
np.unique(random_array_2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a1

array([1, 2, 3])

In [43]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [45]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [47]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [48]:
a3[:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [49]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [50]:
a3[:1,:2,:2]

array([[[1, 2],
        [4, 5]]])

In [51]:
a3[:2,:1,:2]

array([[[ 1,  2]],

       [[10, 11]]])

In [52]:
a4=np.random.randint(10,size=(2,3,4,5))

In [53]:
a4

array([[[[0, 1, 9, 9, 0],
         [4, 7, 3, 2, 7],
         [2, 0, 0, 4, 5],
         [5, 6, 8, 4, 1]],

        [[4, 9, 8, 1, 1],
         [7, 9, 9, 3, 6],
         [7, 2, 0, 3, 5],
         [9, 4, 4, 6, 4]],

        [[4, 3, 4, 4, 8],
         [4, 3, 7, 5, 5],
         [0, 1, 5, 9, 3],
         [0, 5, 0, 1, 2]]],


       [[[4, 2, 0, 3, 2],
         [0, 7, 5, 9, 0],
         [2, 7, 2, 9, 2],
         [3, 3, 2, 3, 4]],

        [[1, 2, 9, 1, 4],
         [6, 8, 2, 3, 0],
         [0, 6, 0, 6, 3],
         [3, 8, 8, 8, 2]],

        [[3, 2, 0, 8, 8],
         [3, 8, 2, 8, 4],
         [3, 0, 4, 3, 6],
         [9, 8, 0, 8, 5]]]])

In [55]:
a4[:,:,:,:1]

array([[[[0],
         [4],
         [2],
         [5]],

        [[4],
         [7],
         [7],
         [9]],

        [[4],
         [4],
         [0],
         [0]]],


       [[[4],
         [0],
         [2],
         [3]],

        [[1],
         [6],
         [0],
         [3]],

        [[3],
         [3],
         [3],
         [9]]]])

## Manipulating array

In [58]:
a1*a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [59]:
a1%2

array([1, 0, 1], dtype=int32)

In [60]:
a2%2

array([[1, 0, 1],
       [0, 1, 0]], dtype=int32)